version: '3.8'

services:
  # Base de datos MySQL compartida - COMENTADO (usando MySQL local)
  # mysql:
  #   image: mysql:8.0
  #   container_name: naturepharma-mysql
  #   restart: unless-stopped
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=Root123!
  #     - MYSQL_DATABASE=naturepharma_db
  #     - MYSQL_USER=naturepharma
  #     - MYSQL_PASSWORD=Root123!
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #     - ./database/init:/docker-entrypoint-initdb.d
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - naturepharma-network
  #   command: --default-authentication-plugin=mysql_native_password

  # Servicio de autenticación
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - DB_HOST=192.168.20.158
      - DB_PORT=3306
      - DB_NAME=auth_service_db
      - DB_USER=naturepharma
      - DB_PASSWORD=Root123!
      - JWT_SECRET=your_super_secret_jwt_key_here
      - JWT_EXPIRES_IN=24h
    # depends_on:
      # - mysql  # Comentado porque ahora usa MySQL local
    networks:
      - naturepharma-network
    restart: unless-stopped
    volumes:
      - ./auth-service/logs:/app/logs

  # Servicio de calendario
  calendar-service:
    build: ./calendar-service
    container_name: calendar-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DB_HOST=192.168.20.158
      - DB_PORT=3306
      - DB_NAME=calendar_service_db
      - DB_USER=naturepharma
      - DB_PASSWORD=Root123!
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    # depends_on:
      # - mysql  # Comentado porque ahora usa MySQL local
    networks:
      - naturepharma-network
    restart: unless-stopped

  # Servicio de laboratorio
  laboratorio-service:
    build: ./laboratorio-service
    container_name: laboratorio-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - DB_HOST=192.168.20.158
      - DB_PORT=3306
      - DB_NAME=laboratorio_db
      - DB_USER=naturepharma
      - DB_PASSWORD=Root123!
      - FRONTEND_URL=http://localhost:3000
      - BASE_URL=http://localhost:3004
    # depends_on:
      # - mysql  # Comentado porque ahora usa MySQL local
    volumes:
      - ./laboratorio-service/uploads:/app/uploads
    networks:
      - naturepharma-network
    restart: unless-stopped

  # Servicio de solicitudes
  solicitudes-service:
    build: ./ServicioSolicitudesOt
    container_name: solicitudes-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=192.168.20.158
      - DB_PORT=3306
      - DB_NAME=sistema_solicitudes
      - DB_USER=naturepharma
      - DB_PASSWORD=Root123!
    # depends_on:
      # - mysql  # Comentado porque ahora usa MySQL local
    volumes:
      - ./ServicioSolicitudesOt/uploads:/app/uploads
    networks:
      - naturepharma-network
    restart: unless-stopped

  # phpMyAdmin para administración de base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: naturepharma-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=192.168.20.158
      - PMA_PORT=3306
      - PMA_USER=naturepharma
      - PMA_PASSWORD=Root123!
      - MYSQL_ROOT_PASSWORD=Root123!
    # depends_on:
      # - mysql  # Comentado porque ahora usa MySQL local
    networks:
      - naturepharma-network
    restart: unless-stopped

  # Nginx como reverse proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: naturepharma-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - auth-service
      - calendar-service
      - laboratorio-service
      - solicitudes-service
    networks:
      - naturepharma-network
    restart: unless-stopped

# volumes:  # Sección comentada porque no se usan volúmenes con MySQL local
  # mysql_data:
    # driver: local

networks:
  naturepharma-network:
    driver: bridge