version: '3.8'

# Docker Compose para desarrollo local
# Uso: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Configuraciones específicas para desarrollo
  auth-service:
    environment:
      - NODE_ENV=development
    volumes:
      - ./auth-service/src:/app/src
      - ./auth-service/logs:/app/logs
    command: npm run dev

  calendar-service:
    environment:
      - NODE_ENV=development
    volumes:
      - ./calendar-service/src:/app/src
    command: npm run dev

  laboratorio-service:
    environment:
      - NODE_ENV=development
    volumes:
      - ./laboratorio-service/src:/app/src
      - ./laboratorio-service/uploads:/app/uploads
    command: npm run dev

  solicitudes-service:
    environment:
      - NODE_ENV=development
    volumes:
      - ./ServicioSolicitudesOt:/app
      - /app/node_modules
    command: npm run dev

  # mysql:  # Comentado porque ahora usa MySQL local
  #   environment:
  #     - MYSQL_GENERAL_LOG=1
  #     - MYSQL_GENERAL_LOG_FILE=/var/lib/mysql/general.log
  #   ports:
  #     - "3306:3306"  # Exponer puerto para acceso directo en desarrollo

  # Servicio adicional para desarrollo: Adminer (alternativa ligera a phpMyAdmin)
  adminer:
    image: adminer:latest
    container_name: naturepharma-adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=host.docker.internal
    # depends_on:
    #   - mysql  # Comentado porque ahora usa MySQL local
    networks:
      - naturepharma-network
    restart: unless-stopped