version: '3.8'

services:
  laboratorio-service:
    build: .
    container_name: laboratorio-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - DB_HOST=192.168.20.158
      - DB_PORT=3306
      - DB_NAME=naturepharma
      - DB_USER=naturepharma
      - DB_PASSWORD=Root123!
      - PORT=3004
      - FRONTEND_URL=http://localhost:3000
      - BASE_URL=http://192.168.20.158:3004
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
    networks:
      - laboratorio-network
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laboratorio-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Root123!
      - MYSQL_DATABASE=naturepharma
      - MYSQL_USER=naturepharma
      - MYSQL_PASSWORD=Root123!
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - laboratorio-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laboratorio-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=Root123!
      - MYSQL_ROOT_PASSWORD=Root123!
    depends_on:
      - mysql
    networks:
      - laboratorio-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  laboratorio-network:
    driver: bridge